# Generated by Django 3.2.13 on 2022-11-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20221128_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.canal', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='video',
            name='comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.comentarios', verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(to='ecommerce.Tag', verbose_name='Tags'),
        ),
    ]
